server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:mem:bell_db
    username: IgorC
    password: unsafepassword
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    #show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console