server:
  port: 8888
spring:
  profiles.active: ${MVC_ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:h2:mem:bell_db
    username: IgorC
    password: unsafepassword
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: embedded
    data: classpath:test-*.sql
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG